// swift-tools-version:6.0

import PackageDescription

let keystoneMCSources: [String] = [
    "Vendor/keystone/llvm/lib/MC/ConstantPools.cpp",
    "Vendor/keystone/llvm/lib/MC/ELFObjectWriter.cpp",
    "Vendor/keystone/llvm/lib/MC/MCAsmBackend.cpp",
    "Vendor/keystone/llvm/lib/MC/MCAsmInfo.cpp",
    "Vendor/keystone/llvm/lib/MC/MCAsmInfoCOFF.cpp",
    "Vendor/keystone/llvm/lib/MC/MCAsmInfoDarwin.cpp",
    "Vendor/keystone/llvm/lib/MC/MCAsmInfoELF.cpp",
    "Vendor/keystone/llvm/lib/MC/MCAssembler.cpp",
    "Vendor/keystone/llvm/lib/MC/MCCodeEmitter.cpp",
    "Vendor/keystone/llvm/lib/MC/MCContext.cpp",
    "Vendor/keystone/llvm/lib/MC/MCELFObjectTargetWriter.cpp",
    "Vendor/keystone/llvm/lib/MC/MCELFStreamer.cpp",
    "Vendor/keystone/llvm/lib/MC/MCExpr.cpp",
    "Vendor/keystone/llvm/lib/MC/MCFragment.cpp",
    "Vendor/keystone/llvm/lib/MC/MCInst.cpp",
    "Vendor/keystone/llvm/lib/MC/MCInstrDesc.cpp",
    "Vendor/keystone/llvm/lib/MC/MCLabel.cpp",
    "Vendor/keystone/llvm/lib/MC/MCObjectFileInfo.cpp",
    "Vendor/keystone/llvm/lib/MC/MCObjectStreamer.cpp",
    "Vendor/keystone/llvm/lib/MC/MCObjectWriter.cpp",
    "Vendor/keystone/llvm/lib/MC/MCParser/AsmLexer.cpp",
    "Vendor/keystone/llvm/lib/MC/MCParser/AsmParser.cpp",
    "Vendor/keystone/llvm/lib/MC/MCParser/COFFAsmParser.cpp",
    "Vendor/keystone/llvm/lib/MC/MCParser/DarwinAsmParser.cpp",
    "Vendor/keystone/llvm/lib/MC/MCParser/ELFAsmParser.cpp",
    "Vendor/keystone/llvm/lib/MC/MCParser/MCAsmLexer.cpp",
    "Vendor/keystone/llvm/lib/MC/MCParser/MCAsmParser.cpp",
    "Vendor/keystone/llvm/lib/MC/MCParser/MCAsmParserExtension.cpp",
    "Vendor/keystone/llvm/lib/MC/MCParser/MCTargetAsmParser.cpp",
    "Vendor/keystone/llvm/lib/MC/MCRegisterInfo.cpp",
    "Vendor/keystone/llvm/lib/MC/MCSection.cpp",
    "Vendor/keystone/llvm/lib/MC/MCSectionCOFF.cpp",
    "Vendor/keystone/llvm/lib/MC/MCSectionELF.cpp",
    "Vendor/keystone/llvm/lib/MC/MCSectionMachO.cpp",
    "Vendor/keystone/llvm/lib/MC/MCStreamer.cpp",
    "Vendor/keystone/llvm/lib/MC/MCSubtargetInfo.cpp",
    "Vendor/keystone/llvm/lib/MC/MCSymbol.cpp",
    "Vendor/keystone/llvm/lib/MC/MCSymbolELF.cpp",
    "Vendor/keystone/llvm/lib/MC/MCTargetOptions.cpp",
    "Vendor/keystone/llvm/lib/MC/MCValue.cpp",
    "Vendor/keystone/llvm/lib/MC/StringTableBuilder.cpp",
    "Vendor/keystone/llvm/lib/MC/SubtargetFeature.cpp",
]

let keystoneTargetSources: [String] = [
    "Vendor/keystone/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp",
    "Vendor/keystone/llvm/lib/Target/AArch64/MCTargetDesc/AArch64AsmBackend.cpp",
    "Vendor/keystone/llvm/lib/Target/AArch64/MCTargetDesc/AArch64ELFObjectWriter.cpp",
    "Vendor/keystone/llvm/lib/Target/AArch64/MCTargetDesc/AArch64MCAsmInfo.cpp",
    "Vendor/keystone/llvm/lib/Target/AArch64/MCTargetDesc/AArch64MCCodeEmitter.cpp",
    "Vendor/keystone/llvm/lib/Target/AArch64/MCTargetDesc/AArch64MCExpr.cpp",
    "Vendor/keystone/llvm/lib/Target/AArch64/MCTargetDesc/AArch64MCTargetDesc.cpp",
    "Vendor/keystone/llvm/lib/Target/AArch64/MCTargetDesc/AArch64TargetStreamer.cpp",
    "Vendor/keystone/llvm/lib/Target/AArch64/TargetInfo/AArch64TargetInfo.cpp",
    "Vendor/keystone/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.cpp",
    "Vendor/keystone/llvm/lib/Target/ARM/AsmParser/ARMAsmParser.cpp",
    "Vendor/keystone/llvm/lib/Target/ARM/MCTargetDesc/ARMAsmBackend.cpp",
    "Vendor/keystone/llvm/lib/Target/ARM/MCTargetDesc/ARMELFObjectWriter.cpp",
    "Vendor/keystone/llvm/lib/Target/ARM/MCTargetDesc/ARMMCAsmInfo.cpp",
    "Vendor/keystone/llvm/lib/Target/ARM/MCTargetDesc/ARMMCCodeEmitter.cpp",
    "Vendor/keystone/llvm/lib/Target/ARM/MCTargetDesc/ARMMCExpr.cpp",
    "Vendor/keystone/llvm/lib/Target/ARM/MCTargetDesc/ARMMCTargetDesc.cpp",
    "Vendor/keystone/llvm/lib/Target/ARM/MCTargetDesc/ARMTargetStreamer.cpp",
    "Vendor/keystone/llvm/lib/Target/ARM/TargetInfo/ARMTargetInfo.cpp",
    "Vendor/keystone/llvm/lib/Target/X86/AsmParser/X86AsmInstrumentation.cpp",
    "Vendor/keystone/llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp",
    "Vendor/keystone/llvm/lib/Target/X86/MCTargetDesc/X86AsmBackend.cpp",
    "Vendor/keystone/llvm/lib/Target/X86/MCTargetDesc/X86ELFObjectWriter.cpp",
    "Vendor/keystone/llvm/lib/Target/X86/MCTargetDesc/X86MCAsmInfo.cpp",
    "Vendor/keystone/llvm/lib/Target/X86/MCTargetDesc/X86MCCodeEmitter.cpp",
    "Vendor/keystone/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp",
    "Vendor/keystone/llvm/lib/Target/X86/TargetInfo/X86TargetInfo.cpp",
]

let keystoneSupportSources: [String] = [
    "Vendor/keystone/llvm/lib/Support/APFloat.cpp",
    "Vendor/keystone/llvm/lib/Support/APInt.cpp",
    "Vendor/keystone/llvm/lib/Support/APSInt.cpp",
    "Vendor/keystone/llvm/lib/Support/ARMBuildAttrs.cpp",
    "Vendor/keystone/llvm/lib/Support/ErrorHandling.cpp",
    "Vendor/keystone/llvm/lib/Support/Hashing.cpp",
    "Vendor/keystone/llvm/lib/Support/IntEqClasses.cpp",
    "Vendor/keystone/llvm/lib/Support/LEB128.cpp",
    "Vendor/keystone/llvm/lib/Support/Memory.cpp",
    "Vendor/keystone/llvm/lib/Support/MemoryBuffer.cpp",
    "Vendor/keystone/llvm/lib/Support/Path.cpp",
    "Vendor/keystone/llvm/lib/Support/Regex.cpp",
    "Vendor/keystone/llvm/lib/Support/ScaledNumber.cpp",
    "Vendor/keystone/llvm/lib/Support/SmallPtrSet.cpp",
    "Vendor/keystone/llvm/lib/Support/SmallVector.cpp",
    "Vendor/keystone/llvm/lib/Support/SourceMgr.cpp",
    "Vendor/keystone/llvm/lib/Support/StringExtras.cpp",
    "Vendor/keystone/llvm/lib/Support/StringMap.cpp",
    "Vendor/keystone/llvm/lib/Support/StringPool.cpp",
    "Vendor/keystone/llvm/lib/Support/StringRef.cpp",
    "Vendor/keystone/llvm/lib/Support/StringSaver.cpp",
    "Vendor/keystone/llvm/lib/Support/TargetParser.cpp",
    "Vendor/keystone/llvm/lib/Support/TargetRegistry.cpp",
    "Vendor/keystone/llvm/lib/Support/Triple.cpp",
    "Vendor/keystone/llvm/lib/Support/Twine.cpp",
    "Vendor/keystone/llvm/lib/Support/raw_ostream.cpp",
    "Vendor/keystone/llvm/lib/Support/regcomp.c",
    "Vendor/keystone/llvm/lib/Support/regerror.c",
    "Vendor/keystone/llvm/lib/Support/regexec.c",
    "Vendor/keystone/llvm/lib/Support/regfree.c",
    "Vendor/keystone/llvm/lib/Support/regstrlcpy.c",
]

let keystoneCoreSources: [String] = [
    "Vendor/keystone/llvm/keystone/ks.cpp",
    "Vendor/keystone/llvm/keystone/EVMMapping.cpp",
]

let keystoneDefines: [String] = [
    "KEYSTONE_STATIC",
    "LLVM_ENABLE_ARCH_ARM",
    "LLVM_ENABLE_ARCH_AArch64",
    "LLVM_ENABLE_ARCH_X86",
    "LLVM_ON_UNIX",
    "__STDC_CONSTANT_MACROS",
    "__STDC_FORMAT_MACROS",
    "__STDC_LIMIT_MACROS",
]

let package = Package(
    name: "Keystone",
    platforms: [
        .iOS(.v12),
        .macOS(.v10_13),
        .tvOS(.v12),
        .watchOS(.v5),
        .visionOS(.v1),
    ],
    products: [
        .library(name: "Keystone", targets: ["Keystone"]),
        .library(name: "CoreKeystone", targets: ["CoreKeystone"]),
    ],
    targets: [
        .target(
            name: "CoreKeystone",
            path: ".",
            exclude: [
                ".github",
                "Script",
                "Tests",
                "LICENSE",
                "README.md",
                ".gitignore",
                ".gitmodules",
            ],
            sources: keystoneMCSources + keystoneTargetSources + keystoneSupportSources + keystoneCoreSources,
            publicHeadersPath: "Sources/Keystone/include",
            cSettings: [
                .define("KEYSTONE_STATIC", to: "1"),
                .headerSearchPath("Sources/Keystone/generated"),
                .headerSearchPath("Vendor/keystone/include"),
                .headerSearchPath("Vendor/keystone/llvm/include"),
                .unsafeFlags(["-Wno-shorten-64-to-32"]),
            ],
            cxxSettings: keystoneDefines.map { .define($0, to: "1") } + [
                .headerSearchPath("Sources/Keystone/generated"),
                .headerSearchPath("Vendor/keystone/include"),
                .headerSearchPath("Vendor/keystone/llvm/include"),
                .headerSearchPath("Vendor/keystone/llvm/keystone"),
                .headerSearchPath("Vendor/keystone/llvm/lib/Target/AArch64"),
                .headerSearchPath("Vendor/keystone/llvm/lib/Target/ARM"),
                .headerSearchPath("Vendor/keystone/llvm/lib/Target/X86"),
                .unsafeFlags(["-UDEBUG", "-Wno-shorten-64-to-32"]),
            ],
            linkerSettings: [
                .linkedLibrary("c++"),
            ]
        ),
        .target(
            name: "Keystone",
            dependencies: ["CoreKeystone"],
            path: "Sources/KeystoneSwift"
        ),
        .testTarget(
            name: "KeystoneTests",
            dependencies: ["Keystone"]
        ),
    ],
    cLanguageStandard: .c11,
    cxxLanguageStandard: .cxx14
)
